"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Your runtime beats 40.52 % of python submissions
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        """
        Method 1

        Your runtime beats 34.35 % of python submissions
        """
        s = list(s)
        t = list(t)
        for ele in s:
            t.remove(ele)

        return t[0]

